### PR TITLE
Show docs download link only if release has docs

### LINKED ISSUE #532: Documentation download links for Erlang packages not working
Documentation download links for Erlang packages are not working.

Steps to reproduce:
1. Go to https://hex.pm/packages/hackney
2. Under the "Links" section, press the "download" link
3. Result: an AccessDenied page is shown.

### PR DESCRIPTION
**Pull request by wojtekmach**
Closes #532

### CODE REVIEW

**Comment by ericmj** [comment]
Since we show the "Online documentation" link we should also show the download link, either we show both or we show none. So we need to find the last release with docs and link to it.

**Comment by wojtekmach** [comment]
Updated

File: lib/hexpm/web/controllers/package_controller.ex [hunk 1]
```diff
@@ -65,12 +65,13 @@ defmodule Hexpm.Web.PackageController do
 
   defp package(conn, package, releases, release, type) do
     release = Releases.preload(release)
+    latest_release_with_docs = Enum.find(releases, & &1.has_docs)
 
     docs_assigns =
       cond do
-        type == :package and Enum.any?(releases, &(&1.has_docs)) ->
+        type == :package and latest_release_with_docs ->
```
Comment (ericmj) [inline lib/hexpm/web/controllers/package_controller.ex]: If there is possibility for `nil` we usually do not use the boolean operators, instead use `&&`.
