### PR TITLE
Display Online documentation link for latest valid version

### LINKED ISSUE #995: Wrong "Online documentation" link when newest release is retired
See below. We should link to the proper latest version, v0.15.7 in this case.

2021-01-04 at 13 23

### PR DESCRIPTION
**Pull request by leandrocp**
Fixes #995

### CODE REVIEW

File: lib/hexpm/utils.ex [hunk 1]
```diff
@@ -281,4 +281,8 @@ defmodule Hexpm.Utils do
   def datetime_to_rfc2822(%DateTime{calendar: Calendar.ISO, time_zone: "Etc/UTC"} = datetime) do
     Calendar.strftime(datetime, "%a, %d %b %Y %H:%M:%S GMT")
   end
+
+  def latest_valid_release_with_docs(releases) do
+    Enum.find(releases, &(&1.has_docs && &1.version.pre == []))
```
Comment (ericmj) [inline lib/hexpm/utils.ex:286]: It's unfortunately not this simple, for example what if a package only has pre-releases. You can extend this function with a `:with_docs` option: https://github.com/hexpm/hexpm/blob/main/lib/hexpm/repository/release.ex#L189.

File: lib/hexpm/repository/release.ex [hunk 2]
```diff
@@ -189,12 +189,20 @@ defmodule Hexpm.Repository.Release do
...
+      if with_docs? do
+        Enum.filter(releases, & &1.has_docs)
+      else
+        releases
+      end
 
     stable_releases =
       if only_stable? do
-        Enum.filter(releases, &(to_version(&1).pre == []))
+        Enum.filter(with_docs_releases, &(to_version(&1).pre == []))
```
Comment (leandrocp) [inline lib/hexpm/repository/release.ex:203]: Is it fine to filter twice to keep the code simpler or better to optimize this?

File: lib/hexpm_web/controllers/package_controller.ex [hunk 3]
```diff
@@ -119,7 +119,8 @@ defmodule HexpmWeb.PackageController do
     repository = package.repository
     release = Releases.preload(release, [:requirements, :downloads, :publisher])
 
-    latest_release_with_docs = Enum.find(releases, & &1.has_docs)
+    latest_release_with_docs =
+      Release.latest_version(releases, only_stable: true, unstable_fallback: true, with_docs: true)
```
Comment (leandrocp) [inline lib/hexpm_web/controllers/package_controller.ex:123]: I assume that `unstable_fallback` should be `true` because if there's just one unstable release, that's the only doc we can display, right?

File: lib/hexpm/repository/release.ex (hunk 2 above)
Comment (ericmj) [reply lib/hexpm/repository/release.ex:203]: Perfectly fine to filter twice 👍

File: lib/hexpm_web/controllers/package_controller.ex (hunk 3 above)
Comment (ericmj) [reply lib/hexpm_web/controllers/package_controller.ex:123]: Correct!

**Review by ericmj — APPROVED** [review]

**Comment by wojtekmach** [comment]
Thank you!

**Comment by leandrocp** [comment]
Thanks for the tips and review :)
