### PR TITLE
Fix an issue with downloads counts in the API

### LINKED ISSUE #524: Download counts are coming back as a list of single-key maps
Recently there was a change which caused the downloads to start coming back as the following instead of just a map with 3 keys. 

```elixir
downloads: [ { all: 2781595 }, { week: 37771 }, { day: 5283 } ]
```

### PR DESCRIPTION
**Pull request by whitfin**
This fixes #524.

Looks like it was caused by some refactoring, so this just merges after the fact to keep the neatened pipeline above.

### CODE REVIEW

File: lib/hexpm/web/views/api/package_view.ex [hunk 1]
```diff
@@ -25,5 +25,10 @@ defmodule Hexpm.Web.API.PackageView do
     |> include_if_loaded(:releases, package.releases, ReleaseView, "minimal.json", package: package)
     |> include_if_loaded(:downloads, package.downloads, DownloadView, "show.json")
     |> include_if_loaded(:owners, package.owners, UserView, "minimal.json")
+    |> group_downloads()
+  end
+
+  defp group_downloads(%{downloads: downloads} = package) do
+    Map.put(package, :downloads, Enum.reduce(downloads, %{}, &Map.merge(&1, &2)))
```
Comment (ericmj) [inline lib/hexpm/web/views/api/package_view.ex]: This will crash if the downloads are not loaded. You need a clause for if there are no downloads.

Comment (josevalim) [inline lib/hexpm/web/views/api/package_view.ex]: Maybe it should crash though? Why would you call it without downloads?

Comment (ericmj) [inline lib/hexpm/web/views/api/package_view.ex]: All the views are written under the assumption that no associations are guaranteed. It makes it easier to use the views from different controllers that doesn't load the same data.

**Comment by whitfin** [comment]
@ericmj I added a clause for downloads missing, let me know if you'd like anything else changing!

**Comment by ericmj** [comment]
Thank you @whitfin!
